In [ ]:
import torch

x = torch.randint(0, 10, (3,))
x

tensor([7, 9, 0])

In [ ]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x0 = torch.randn(50, 1, 64, 64).to(device)
t = torch.rand(x0.shape[0], 1, 1, 1).to(device)
t

tensor([[[[0.6986]]],


        [[[0.5994]]],


        [[[0.9387]]],


        [[[0.2764]]],


        [[[0.5495]]],


        [[[0.0824]]],


        [[[0.8161]]],


        [[[0.6792]]],


        [[[0.3067]]],


        [[[0.0440]]],


        [[[0.0507]]],


        [[[0.9400]]],


        [[[0.2564]]],


        [[[0.0559]]],


        [[[0.8562]]],


        [[[0.5124]]],


        [[[0.7769]]],


        [[[0.6829]]],


        [[[0.1240]]],


        [[[0.6491]]],


        [[[0.7381]]],


        [[[0.7989]]],


        [[[0.7172]]],


        [[[0.4813]]],


        [[[0.6184]]],


        [[[0.3329]]],


        [[[0.2664]]],


        [[[0.2293]]],


        [[[0.2211]]],


        [[[0.9957]]],


        [[[0.7259]]],


        [[[0.1865]]],


        [[[0.6390]]],


        [[[0.2906]]],


        [[[0.1764]]],


        [[[0.7125]]],


        [[[0.3001]]],


        [[[0.3906]]],


        [[[0.3382]]],


        [[[0.3124]]],


        [[[0.5702]]],


        [[[0.636

In [ ]:
t_steps = torch.linspace(0, 1, 100, device=device)
dt = t_steps[1] - t_steps[0]
dt

tensor(0.0101, device='cuda:0')

In [ ]:
import numpy as np
out = np.random.rand(100)
out

array([0.55729391, 0.65582293, 0.77574011, 0.48124262, 0.51789038,
       0.29323706, 0.33192807, 0.22061008, 0.37556035, 0.93856198,
       0.48894145, 0.36215072, 0.21762654, 0.07232691, 0.34397467,
       0.0808026 , 0.99935689, 0.45802286, 0.48204752, 0.01416718,
       0.19953179, 0.40070069, 0.76752143, 0.9869094 , 0.2030038 ,
       0.18667607, 0.35222776, 0.61265722, 0.08956331, 0.17728432,
       0.07363688, 0.60375169, 0.09438713, 0.21878827, 0.53012971,
       0.6100876 , 0.06616257, 0.47714812, 0.3117948 , 0.38872331,
       0.28579481, 0.22578603, 0.05940899, 0.55775242, 0.77350137,
       0.05942038, 0.54975384, 0.02707839, 0.47112928, 0.90735437,
       0.30605083, 0.83864884, 0.40803984, 0.70869132, 0.85599085,
       0.76628425, 0.10487731, 0.30797273, 0.12578546, 0.16934567,
       0.58481862, 0.03195766, 0.21336071, 0.70126945, 0.39268292,
       0.59265074, 0.93099173, 0.2329043 , 0.22070094, 0.40876846,
       0.4037246 , 0.83035367, 0.22702832, 0.45021681, 0.55302

In [5]:
from diffusers import AutoencoderKL
from modelscope import StableDiffusionPipeline

model = "stabilityai/your-stable-diffusion-model"
vae = AutoencoderKL.from_pretrained("stabilityai/sdxl-vae")
pipe = StableDiffusionPipeline.from_pretrained(model, vae=vae)

PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.


IndexError: list index out of range

In [3]:
from diffusers import AutoencoderKL

vae_dir = '/root/.cache/huggingface/hub/models--stabilityai--sdxl-vae/snapshots/6f5909a7e596173e25d4e97b07fd19cdf9611c76'
vae = AutoencoderKL.from_pretrained(vae_dir)

